services:

  redis:
    image: redis:latest
    container_name: wpp_bot_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    depends_on:
      - redis
    environment:
      - WAHA_PRINT_QR=true
    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./data/chroma_data:/app/data/chroma_data
    depends_on:
      - redis
      - waha
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}

volumes:
  redis_data:
