services:

  redis:
    image: redis:latest
    container_name: wpp_bot_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    depends_on:
      - redis
    environment:
      - WAHA_PRINT_QR=false
    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data
    depends_on:
      - redis
      - waha
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
      - RAG_SEARCH_K=${RAG_SEARCH_K}
      - RAG_CHUNK_SIZE=${RAG_CHUNK_SIZE}
      - RAG_CHUNK_OVERLAP=${RAG_CHUNK_OVERLAP}
      - RAG_DATA_DIR=${RAG_DATA_DIR}
      - CHROMA_PERSIST_DIR=${CHROMA_PERSIST_DIR}
      - WAHA_API_URL=${WAHA_API_URL}
      - WAHA_SESSION=${WAHA_SESSION}
      - REDIS_URL=${REDIS_URL}
      - BUFFER_KEY_SUFIX=${BUFFER_KEY_SUFIX}
      - DEBOUNCE_SECONDS=${DEBOUNCE_SECONDS}
      - BUFFER_TTL=${BUFFER_TTL}
      - MAX_HISTORY_MESSAGES=${MAX_HISTORY_MESSAGES}
      - HISTORY_TTL_HOURS=${HISTORY_TTL_HOURS}

volumes:
  redis_data:
